### ISSUE TITLE
[CC-PORTAL-FEEDBACK] The rationale should be showing for these votes. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#402] opened 2024-10-09 09:15 UTC
**Taken at**: https://constitution.gov.tools/en/latest-updates
**Fields**:
- Noticed an issue?: The rationale should be showing for these votes. 

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/e3400356-70b9-442d-b043-21547675fc94-annotated_77ed81de-3601-4bf9-8d28-bb739a1bbbcf.png?etag=22d8f8aa16484518c0d5d8e43bb1f926)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/e3400356-70b9-442d-b043-21547675fc94-annotated_77ed81de-3601-4bf9-8d28-bb739a1bbbcf.png?etag=22d8f8aa16484518c0d5d8e43bb1f926)*

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1368x785
**[Open #14 in Usersnap](https://app.usersnap.com/l/feedback/c77ec804-4840-4eef-8d53-403e74840475?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Thomas-Upfield** [comment] 2024-10-11 13:45
@Kale98 do you yet have any idea as to why the rationales are not being displayed?

**Comment by Kale98** [comment] 2024-10-14 11:01
@Thomas-Upfield This issue seams to be caused by the failed connection between Redis and IPFS service. We have reinstalled the services and according to the logs it should be working now. Since we cannot add rationale, do you think you can test that so we can confirm it is working now?
cc @bosko-m

**Comment by bosko-m** [comment] 2024-10-15 09:28
As per @Thomas-Upfield comment, if the metadata anchor is stored on chain, why do we need to save it in the database?

**Comment by bosko-m** [comment] 2024-10-23 13:35
Impact of rationale not being visible in the application is that people who submitted rationale through the app, most likely didnt get the link to ipfs which means they knew that they were affected or they didnt expect the link at all
All of them actually voted through CLI providing CIP-136 compliant rationale as it can be verified through DBSync records.
Will be addressed in #411 initially then full compliance with CIP-136 should be implemented through #417.

**Closed by bosko-m** 2024-10-23 13:35 UTC
Labels: usersnap-bug
